version: "3.9"

services:
  e-commerce:
    container_name: e-commerce
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    environment:
      DEBUG: 1
    volumes:
      - .:/app
    ports:
      - 80:80
    restart: on-failure

  mysql:
    platform: linux/x86_64
    image: mysql
    restart: always
    command: --innodb_use_native_aio=0
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: Piotrek120
      MYSQL_DATABASE: ecommerce

  redis:
    image: redislabs/rejson:latest
    restart: always
    command: redis-server --loadmodule /usr/lib/redis/modules/rejson.so --save 20 1 --loglevel warning --requirepass Piotrek120
    ports:
      - 127.0.0.1:6380:6379
    volumes:
      - ./redis_cache:/var/lib/redis
